//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _888MarketplaceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Product_Order = new HashSet<Product_Order>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public string Note { get; set; }
        public int BuyerId { get; set; }
        public int PaymentId { get; set; }
        public int DeliveryId { get; set; }
        public Nullable<int> VoucherId { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order> Product_Order { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
