//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _888MarketplaceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher_Redemption
    {
        public int Id { get; set; }
        public int VoucherId { get; set; }
        public int BuyerId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
