//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _888MarketplaceApp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public string Note { get; set; }
        public int BuyerId { get; set; }
        public int PaymentId { get; set; }
        public int DeliveryId { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
